version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        environment:
         BUNDLE_JOBS: 3
         BUNDLE_RETRY: 3
         BUNDLE_PATH: vendor/bundle
         PGHOST: 127.0.0.1
         PGUSER: circleci-demo-ruby
         RAILS_ENV: test
    steps:
      - checkout
      
      - restore_cache:
         keys:
          - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          - rails-demo-bundle-v2-
      - run:
         name: Run bundle install
         command: bundle check || bundle install
         
      - save_cache:
         key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
         paths:
          - vendor/bundle
         
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
          
      - run: bundle exec rails db:create
      
      - run :bundle exec rails db:schema:load
        
      - run:
          name: Run rails test
          command: bundle exec rails test test/system