version: 2.1
jobs:
  build:
    parallelism: 3 
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        environment:
         BUNDLE_JOBS: 3
         BUNDLE_RETRY: 3
         BUNDLE_PATH: vendor/bundle
         PGHOST: 127.0.0.1
         PGUSER: circleci-demo-ruby
         RAILS_ENV: test
    steps:
      - checkout
      
      - run:
          name: Bundler を指定
          command: bundle -v
      
      - restore_cache:
         keys:
          - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          - rails-demo-bundle-v2-
          
      - run:
         name: バンドルインストール
         command: bundle check || bundle install
         
      - save_cache:
         key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
         paths:
          - vendor/bundle
         
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

      - run:
          name: minitest
          command: rails test test/system