name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6.3
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Install dependent libralies
        run: sudo apt-get install libmysqlclient-dev
      - name: Set up bundler
        run: gem install bundler
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
      - name: Run test
        run: |
          bin/rails test
      - name: Run system test
        run: |
          bin/rails test:system
